powerpc: fix a compile error regarding fsl_guts.h
Got a compile error:
arch/powerpc/sysdev/fsl_rcpm.c:22:26: fatal error: asm/fsl_guts.h: No
such file or directory

The following patch moved arch/powerpc/include/asm/fsl_guts.h to
include/linux/fsl/guts.h, but failed to change the file path in
arch/powerpc/sysdev/fsl_rcpm.c.
commit b97dec3d956a ("powerpc/fsl: Move fsl_guts.h out of arch/powerpc")

Signed-off-by: Chenhui Zhao <chenhui.zhao@nxp.com>