clocksource: arch_timer: export arm_arch_timer_reread symbol
The symbol needs to be accesible by modules, for example tcrypt,
thus export it:

ERROR: "arm_arch_timer_reread" [crypto/tcrypt.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
make: *** Waiting for unfinished jobs....

Fixes: 344ca1046f768 ("clocksource: arm_arch_timer: Timer reread erratum")
Signed-off-by: Horia Geantă <horia.geanta@nxp.com>