kernel: smp: fix the bug: array index in initializer exceeds array bounds
Because the NR_IPI is set to 9, IPI_BAREMETAL_COMM is used in array ipi_types.
And the current value of IPI_BAREMETAL_COMM is 9, which will cause issue:
arch/arm/kernel/smp.c:562:4: error: array index in initializer exceeds array bounds

workaround:
switch IPI_BAREMETAL_COMM and IPI_IPIPE_FIRST, because IPI_IPIPE_FIRST
is not used in array ipi_types.

Signed-off-by: Jerry Huang <jerry.huang@nxp.com>